repos:
  - repo: https://github.com/TekWizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-mod-tidy-repo
      - id: golangci-lint-mod
        args: [--fix]

  - repo: local
    hooks:
      - id: go-generate
        name: go-generate
        entry: go generate -x ./...
        language: system
        pass_filenames: false
